name: Scheduled build

on: [push]
# on:
#   schedule:
#     # 月曜日の 11:00 (JST) に処理を実行する。
#     # UTC の 02:00 は JST だと 11:00 。
#     - cron: '20 8 * * *'

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build --verbose
      - name: Create .env file
        run: |
          touch .env
          echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}" >> .env
          echo "TEST_KEY=${TEST_KEY}" >> .env
          cat .env
        env: 
          TEST_KEY: ${{ secrets.TEST_KEY }} 
      - name: Run tests
        run: cargo run --verbose
